name    'jtslear-play'
version '0.0.1'
source 'UNKNOWN'
author 'jtslear'
license 'Apache License, Version 2.0'
summary 'Deploy the play server'
description 'Deploy version 3 of play allowing some awesome music'
project_page 'https://github.com/jtslear/puppet-play'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/vcsrepo', '>=0.1.2'
dependency 'alup/rbenv', '>=1.2.0'
dependency 'puppetlabs/mysql', '>=0.9.0'
dependency 'puppetlabs/apt', '>=1.2.0'
dependency 'puppetlabs/stdlib', '>=4.1.0'
